spring:
  application:
    name: backend

  config:
    import: "classpath:configuration/etc/security-whitelist.yml"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fms2014
    username: root
    password: "!rlatjrdyd8750"
    hikari:
      maximum-pool-size: 30
      pool-name: "Hikari Connection Pool"  # Pool Name Alias
      minimum-idle: 10
      idle-timeout: 10000
      connection-timeout: 3000
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: .html
    view-names: thymeleaf/*
    cache: false
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: .jsp
  messages:
    encoding: "UTF-8"
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true

logging:
  config: "classpath:configuration/log4j/log4j2.yaml"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: "com.portfolio.backend.dto"
  mapper-locations: "classpath*:mapper/*.xml"

management:
  endpoints:
    web:
      exposure:
        include: "env,health" # env 엔드포인트를 웹으로 노출

springdoc:
  api-docs:
    enabled: true
    path: "/spring-boot/study"
  swagger-ui:
    path: "/swagger-ui.html"
    # 정적 리소스 핸들러 경로에 맞춰 설정
    # layout: BaseLayout
    enabled: true
    # 아래 부분이 핵심입니다. 커스텀 CSS와 JS를 주입합니다.
    # 주의: addResourceHandlers에서 /swagger-custom/ 경로를 매핑해줘야 할 수도 있습니다.
    # 기본 static 폴더에 있다면 바로 접근 가능합니다.
    # tags-sorter: alpha
    # operations-sorter: alpha