spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fms2014
    username: root
    password: "!rlatjrdyd8750"
    hikari:
      maximum-pool-size: 30
      pool-name: "Hikari Connection Pool"  # Pool Name Alias
      minimum-idle: 10
      idle-timeout: 10000
      connection-timeout: 3000
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: .html
    view-names: thymeleaf/*
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: .jsp
  messages:
    encoding: "UTF-8"

logging:
  config: "classpath:configuration/log4j/log4j2.yaml"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: "com.portfolio.backend.dto"
  mapper-locations: "classpath*:mapper/*.xml"

server:
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: "env,health" # env 엔드포인트를 웹으로 노출