spring:
  application:
    name: backend

  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/fms2014
      username: root
      password: ""
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: "Hikari Connection Pool"  # Pool Name Alias
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 3000
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  config: "classpath:configuration/log4j/log4j2.yaml"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: "com.portfolio.backend.dto"
  mapper-locations: "classpath*:mapper/*.xml"